name: Baseline Oracle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  baseline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Build workspace
        run: pnpm -r build

      - name: Scan changed files (fallback to repo)
        run: |
          # Try diff-only first; if nothing, scan repo
          pnpm scan -- --out .baseline/scan.json --target widely --changed || true
          if [ ! -s ".baseline/scan.json" ]; then
            pnpm scan -- --out .baseline/scan.json --target widely .
          fi

      - name: Generate HTML report
        run: pnpm report -- .baseline/scan.json --html .baseline/report.html

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: baseline-report
          path: .baseline/report.html
          if-no-files-found: error
          retention-days: 7

      - name: Enforce policy
        env:
          BASELINE_MAX_RISK: "70"
          BASELINE_BLOCK_NOT_BASELINE: "true"
        run: node scripts/policy.js
