name: Baseline Oracle

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  baseline:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: Build workspace
        run: pnpm -r build

      - name: Scan repository
        run: npx baseline scan "src/**/*.{css,scss,js,jsx,ts,tsx}" demo.css --out .baseline/scan.json

      - name: Generate HTML report
        run: npx baseline report .baseline/scan.json --html .baseline/report.html

      - name: Annotate PR (inline errors)
        run: npx baseline annotate .baseline/scan.json

      - name: Enforce policy
        run: npx baseline policy .baseline/scan.json

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: baseline-report
          path: .baseline/report.html
          retention-days: 7
